import { RawSpace, inferred, normalize } from "./space";
const e = inferred(
  "체험용 예시 데이터이며 실제 업로드 사진을 분석한 결과가 아닙니다.",
);
export const example: RawSpace = {
  loft: null,
  version: "1.0",
  unit: "m",
  shell: { width: 4, depth: 5, height: 2.4, evidence: e },
  zones: [
    {
      id: "bath",
      name: "화장실",
      x: 2.5,
      z: 0,
      width: 1.5,
      depth: 1.7,
      evidence: e,
    },
    {
      id: "living",
      name: "방",
      x: 0,
      z: 0,
      width: 4,
      depth: 5,
      evidence: e,
    },
  ],
  partitions: [
    {
      id: "bath-left",
      axis: "z",
      x: 2.5,
      z: 0,
      length: 1.7,
      height: 2.4,
      evidence: e,
    },
    {
      id: "bath-bottom",
      axis: "x",
      x: 2.5,
      z: 1.7,
      length: 1.5,
      height: 2.4,
      evidence: e,
    },
  ],
  openings: [
    {
      id: "entry-door",
      kind: "door",
      wallId: "north",
      offset: 0.3,
      width: 0.85,
      height: 2.05,
      sill: 0,
      evidence: e,
    },
    {
      id: "bath-door",
      kind: "door",
      wallId: "bath-bottom",
      offset: 0.2,
      width: 0.75,
      height: 2,
      sill: 0,
      evidence: e,
    },
    {
      id: "window",
      kind: "window",
      wallId: "south",
      offset: 1,
      width: 2,
      height: 1.25,
      sill: 0.85,
      evidence: e,
    },
  ],
  furniture: [
    {
      id: "bed",
      identity: "bed-1",
      kind: "bed",
      name: "침대",
      x: 0.8,
      z: 3.8,
      width: 1.25,
      depth: 2,
      height: 0.48,
      rotation: 0,
      evidence: e,
    },
    {
      id: "desk",
      identity: "desk-1",
      kind: "desk",
      name: "책상",
      x: 3.55,
      z: 3.6,
      width: 1.2,
      depth: 0.6,
      height: 0.75,
      rotation: 90,
      evidence: e,
    },
    {
      id: "chair",
      identity: "chair-1",
      kind: "chair",
      name: "의자",
      x: 2.95,
      z: 3.6,
      width: 0.45,
      depth: 0.45,
      height: 0.8,
      rotation: 90,
      evidence: e,
    },
    {
      id: "sink",
      identity: "sink-1",
      kind: "sink",
      name: "싱크대",
      x: 1.85,
      z: 0.35,
      width: 1.1,
      depth: 0.6,
      height: 0.85,
      rotation: 0,
      evidence: e,
    },
    {
      id: "fridge",
      identity: "fridge-1",
      kind: "fridge",
      name: "냉장고",
      x: 0.35,
      z: 1.4,
      width: 0.55,
      depth: 0.6,
      height: 1.5,
      rotation: 0,
      evidence: e,
    },
    {
      id: "washer",
      identity: "washer-1",
      kind: "washer",
      name: "세탁기",
      x: 3.6,
      z: 0.4,
      width: 0.6,
      depth: 0.6,
      height: 0.85,
      rotation: 0,
      evidence: e,
    },
    {
      id: "toilet",
      identity: "toilet-1",
      kind: "toilet",
      name: "변기",
      x: 2.95,
      z: 0.45,
      width: 0.45,
      depth: 0.65,
      height: 0.65,
      rotation: 0,
      evidence: e,
    },
    {
      id: "closet",
      identity: "closet-1",
      kind: "wardrobe",
      name: "옷장",
      x: 0.4,
      z: 2.15,
      width: 0.65,
      depth: 0.65,
      height: 1.95,
      rotation: 0,
      evidence: e,
    },
  ],
  connections: [{ from: "living", to: "bath", evidence: e }],
  assumptions: [
    "20㎡의 직사각형 원룸을 가정한 체험용 공간입니다.",
    "방 하나에 작은 화장실이 딸린 예시입니다. 주방과 현관을 별도 방으로 나누지 않습니다.",
  ],
};
export const demoSpace = normalize(example, 20, 0, { illustrativeDemo: true });

const loftExample: RawSpace = structuredClone(example);
loftExample.shell.height = 4.2;
loftExample.partitions.forEach((p) => (p.height = 2.05));
loftExample.loft = {
  x: 0,
  z: 0,
  width: 4,
  depth: 2,
  elevation: 2.2,
  furnitureIds: [],
  stairs: { side: "south", offset: 1.7, width: 0.8, run: 2.3, evidence: e },
  evidence: e,
};
loftExample.furniture = loftExample.furniture.filter((f) => f.kind !== "bed");
loftExample.furniture.push({
  id: "upper-bed",
  identity: "upper-bed",
  kind: "bed",
  name: "복층 침대",
  x: 1.2,
  z: 1,
  width: 1.4,
  depth: 1.8,
  height: 0.4,
  rotation: 0,
  evidence: e,
});
loftExample.loft.furnitureIds = ["upper-bed"];
loftExample.assumptions = [
  "체험용 복층 예시이며 업로드 사진에서 재구성한 결과가 아닙니다.",
];
export const loftDemoSpace = normalize(loftExample, 20, 0, {
  illustrativeDemo: true,
});
